# Generated by Django 5.0.6 on 2024-05-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catid', models.CharField(max_length=250)),
                ('categoryname', models.CharField(max_length=250)),
                ('handle', models.CharField(max_length=250)),
                ('categoryhomeimage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('categorysectionimage', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[], max_length=100)),
                ('categoryid', models.CharField(editable=False, max_length=100, null=True)),
                ('handle', models.CharField(editable=False, max_length=100, null=True)),
                ('categoryname', models.CharField(editable=False, max_length=100, null=True)),
            ],
        ),
    ]
