# Generated by Django 5.0.6 on 2024-05-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamimi_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catid', models.CharField(max_length=250)),
                ('categoryname', models.CharField(max_length=250)),
                ('handle', models.CharField(max_length=250)),
            ],
        ),
    ]
