# Generated by Django 5.0.6 on 2024-05-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamimi_admin', '0002_categorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryinfomodel',
            name='categoryname',
            field=models.CharField(editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='categoryinfomodel',
            name='handle',
            field=models.CharField(editable=False, max_length=250),
        ),
    ]
