# Generated by Django 5.0.6 on 2024-05-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamimi_admin', '0003_alter_categoryinfomodel_categoryname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryinfomodel',
            name='catid',
            field=models.CharField(editable=False, max_length=250),
        ),
    ]
