# Generated by Django 5.0.6 on 2024-06-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamimi_admin', '0004_alter_categoryinfomodel_catid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catid', models.CharField(editable=False, max_length=250)),
                ('subcatid', models.CharField(editable=False, max_length=250)),
                ('categorysectionimage', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceModel',
        ),
    ]
