# Generated by Django 5.0.6 on 2024-06-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamimi_admin', '0006_delete_categorysectionmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catid', models.CharField(editable=False, max_length=250)),
                ('subcatid', models.CharField(editable=False, max_length=250)),
                ('categorysectionimage', models.ImageField(blank=True, null=True, upload_to='sectionimages/')),
            ],
        ),
        migrations.AlterField(
            model_name='categoryinfomodel',
            name='categoryhomeimage',
            field=models.ImageField(blank=True, null=True, upload_to='homeimages/'),
        ),
        migrations.AlterField(
            model_name='categoryinfomodel',
            name='categorysectionimage',
            field=models.ImageField(blank=True, null=True, upload_to='sectionimages/'),
        ),
    ]
