# Generated by Django 5.0.6 on 2024-06-10 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamimi_admin', '0007_categorysectionmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceimage', models.ImageField(blank=True, null=True, upload_to='deviceimages/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tamimi_admin.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ParentSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentsectionname', models.CharField(max_length=250)),
                ('parentsectionimage', models.ImageField(blank=True, null=True, upload_to='parentsectionimages/')),
            ],
        ),
        migrations.CreateModel(
            name='SectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionimage', models.ImageField(blank=True, null=True, upload_to='sectionimages/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tamimi_admin.categorymodel')),
                ('parentsection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tamimi_admin.parentsectionmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='CategorySectionModel',
        ),
    ]
