# Generated by Django 5.0.6 on 2024-06-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamimi_admin', '0008_devicemodel_parentsectionmodel_sectionmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryInfoModel',
        ),
    ]
