# Generated by Django 5.0.6 on 2024-06-13 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamimi_admin', '0009_delete_categoryinfomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_category', to='tamimi_admin.categorymodel'),
        ),
    ]
